name: pos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  cached_network_image: ^3.4.1
  esc_pos_utils_plus: ^2.0.4
  file_picker: ^10.3.3
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  flutter_thermal_printer: ^2.0.1
  go_router: ^17.2.0
  google_fonts: ^8.0.2
  http: ^1.6.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.10.2
  printing: ^5.13.4
  provider: ^6.1.5+1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.5
  syncfusion_flutter_xlsio: ^31.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
